services:
- type: web
  name: phong_thuy_so
  buildCommand: npm run build
  publishDir: dist
  env: static
  # Xóa phần startCommand vì không cần
  routes:
    - type: rewrite
      source: /*
      destination: /index.html